language: java
jdk: openjdk6
install: ''
before_script:
  - mkdir -p target
  - gpg --import secring.gpg
  - echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?><settings><profiles><profile><id>gpg</id><activation><activeByDefault>true</activeByDefault></activation><properties><gpg.passphrase>$GPG_PASSPHRASE</gpg.passphrase></properties></profile></profiles><servers><server><id>sonatype-nexus-snapshots</id><username>nebhale</username><password>$NEXUS_PASSWORD</password></server><server><id>sonatype-nexus-staging</id><username>nebhale</username><password>$NEXUS_PASSWORD</password></server></servers></settings>" > target/settings.xml
script: mvn --quiet --settings target/settings.xml source:jar javadoc:jar deploy
after_script: rm -f target/settings.xml $HOME/.gnupg/secring.gpg
env:
  global:
    - secure: "LM9F3yc0eZHrV2/y/PJPlTQ4oiaVkqcgl2ajlmCpbRnedqgEXvIOJdLZOfRT\n/zNQh0XTmXKIsOie1JPxu7FlMJVxWmZwxifAi11cnGXKXWkh5Q8HmaAMSMnR\nIfd/7CXu3qZ09NbLy/uzY8X8zecyDhNRgxAAo+nY34rpB5bp8Is=" # $NEXUS_PASSWORD
    - secure: "gRj6CNAgejvM85znhJYSPW9+eTLQC3Y/wouwltTA6c8TpRgeAP5I1nQ6asut\nm2ZfmleJkZim9zhbEp32P7ZipWbJgH/sfPQhfRSmlO8KEdMKzr6sQtIT3g2a\nIPSZbo3veK4OPVUTdktd/pWKkHZPHl963oU69MpvXif7fHxmUqI=" # $GPG_PASSPHRASE
